---
title: "Tidy-Tuesday_2019-12-17"
author: "Adrienne"
date: "December 17, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)


```

```{r}
# Get the Data

dog_moves <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-12-17/dog_moves.csv')
dog_travel <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-12-17/dog_travel.csv')
dog_descriptions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-12-17/dog_descriptions.csv')

```

Checking out dog_descrptions, there's some immediate questions that pop up. Is there one sex of dog that is more often found at shelters? Which age of dog is more common? Does sex relate to breed, i.e. are there some breeds that people don't want males or females of over others? What pure breeds end up in the pound? 

First, lets look at sex of dogs found at the pound
```{r}


dogs_sex <- dog_descriptions %>%
  filter(!sex == "Unknown") %>%
  group_by(sex) %>%
  count(sex) %>%
  ungroup()

percent <- c(dogs_sex$n[1]/sum(dogs_sex$n), dogs_sex$n[2]/sum(dogs_sex$n))
binom_f <- binom.test(dogs_sex$n[1],(dogs_sex$n[1] + dogs_sex$n[2]),0.5)
binom_m <- binom.test(dogs_sex$n[2],(dogs_sex$n[1] + dogs_sex$n[2]),0.5)

pvalue <- c(binom_f[[3]], binom_m[[3]])
conf_low  <- c(binom_f[[4]][[1]], binom_m[[4]][[1]])
conf_high <- c(binom_f[[4]][[2]], binom_m[[4]][[2]])

true_low <- confidence_low * sum(dogs_sex$n)
true_high <- confidence_high * sum(dogs_sex$n)

dogs_sex %>%
  mutate(percent   = percent,
         p         = pvalue,
         conf_low  = conf_low,
         conf_high = conf_high,
         true_low  = true_low,
         true_high = true_high)
```

``` {r}
dogs_sex %>%
ggplot(aes(sex, n)) +
  geom_bar(stat = "identity", fill = "lightblue", width = 0.5) +
  geom_errorbar(aes(ymin = true_low, ymax = true_high), width = 0.25, color = "orange")

```

